import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css'; // This line imports your Tailwind-configured CSS
import App from './App'; // This imports your main App component
import reportWebVitals from './reportWebVitals'; // For performance reporting, default from Create React App

// Create a React root to render your application
const root = ReactDOM.createRoot(document.getElementById('root'));

// Render the App component into the root element
root.render( <
    React.StrictMode >
    <
    App / >
    <
    /React.StrictMode>
);

// Function to report web vitals (optional, generated by Create React App)
reportWebVitals();